// LanguageContext.jsx
'use client' // Add this directive at the top

import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  // Set default language to Arabic
  const [currentLanguage, setCurrentLanguage] = useState('ar');

  const translations = {
    en: {
      home: 'Home',
      services: 'Services',
      plans: 'Plans',
      transportation: 'Transportation',
      hotels: 'Hotels',
      residence: 'Residence',
      contact: 'Contact',
      getToKnowRussia: 'Get to Know Russia',
      restaurants: 'Restaurants',
      touristAttractions: 'Tourist Attractions',
      events: 'Events',
      shopping: 'Shopping',
      museums: 'Museums',
      naturalPlaces: 'Natural Places',
      adminLogin: 'Admin Login',
      shareOnSocial: 'Share on Social Media',
      companyLocation: 'Company Location',
      viewOnMap: 'View on Google Maps',
      // Hero section translations
      heroTitle: 'Ruento Tourism',
      heroDescription: 'Experience Russia like never before with our premium tour services. As the leading tourism provider specializing in Russian destinations, we offer meticulously crafted experiences that blend rich cultural heritage, breathtaking landscapes, and unparalleled hospitality.',
      contactUs: 'Contact Us',
      email: 'Email address',
      password: 'Password',
      signin: 'Sign in',
      signingin: 'Signing in ...',
      backtohome: 'Back to Home page ←',
      invalidCredentials: 'Invalid email or password',
      loginSuccess: 'Login successful!',
      welcomeAdmin: 'Welcome Admin',
      dashboard: 'Dashboard',
      logout: 'Logout',
      manageHeroVideo: 'Manage the hero video on the homepage',
      updateTripInfo: 'Update the next trip date information',
      manageServices: 'Manage services cards (Plans, Transportation, etc.)',
      manageRussiaCategories: 'Manage Russia categories (Restaurants, Museums, etc.)',
      manageBlogPosts: 'Create and manage blog posts',
      manageTranslations: 'Manage translations and language content',
      manage: 'Manage',
      recentActivity: 'Recent Activity',
      heroSection: 'Hero Section',
      russiaCategories: 'Russia Categories',
      blogPosts: 'Blog Posts',
      languageContent: 'Language Content',
      ourServices: 'Our Services',
      servicesDescription: 'Discover our comprehensive travel services designed to make your Russian adventure unforgettable',
      learnMore: 'Learn More',
      noServices: 'No services available at the moment. Please check back later.',
      discoverRussia: 'Discover the diverse beauty and rich culture of Russia through its many attractions',
      addItem: 'Add Item',
      noItems: 'No items added yet. Click "Add Item" to get started.',
      item: 'Item',
      images: 'Images',
      uploadImage: 'Upload Image',
      saving: 'Saving...',
      save: 'Save Changes',
      noContent: 'No content available for this category yet.',
      manageBlog: 'Manage Blog',
      createBlog: 'Create New Blog Post',
      editBlog: 'Edit Blog Post',
      existingBlogs: 'Existing Blog Posts',
      noBlogs: 'No blog posts yet. Create your first one!',
      by: 'By',
      title: 'Title',
      author: 'Author',
      excerpt: 'Excerpt',
      content: 'Content',
      create: 'Create',
      update: 'Update',
      cancel: 'Cancel',
      blog: 'Blog',
      blogDescription: 'Discover the latest news, tips, and stories about traveling in Russia',
      blogNotFound: 'Blog post not found',
      backToBlog: 'Back to Blog',
      readMore: 'Read More',
      latestFromBlog: 'Latest From Our Blog',
      blogSectionDescription: 'Discover travel tips, cultural insights, and exciting destinations in Russia',
      viewAllBlogs: 'View All Blog Posts',
      contactDescription: 'Get in touch with us for any questions about our services or to plan your next trip to Russia',
      getInTouch: 'Get In Touch',
      phone: 'Phone',
      address: 'Address',
      officeHours: 'Office Hours',
      hours: 'Monday - Friday: 9AM - 6PM',
      visitUs: 'Visit Us',
      mapPlaceholder: 'Interactive map would appear here',
      sendMessage: 'Send us a Message',
      yourName: 'Your Name',
      yourEmail: 'Your Email',
      subject: 'Subject',
      message: 'Message',
      sending: 'Sending...',
      contactSuccess: 'Thank you for your message! We will get back to you soon.',
      footerDescription: 'Experience Russia like never before with our premium tour services. Discover the beauty and culture of Russia with expert guides.',
      quickLinks: 'Quick Links',
      discoverRussia: 'Discover Russia',
      contactInfo: 'Contact Info',
      newsletter: 'Subscribe to our Newsletter',
      newsletterDescription: 'Get the latest news and updates about our services and offers.',
      subscribe: 'Subscribe',
      allRightsReserved: 'All rights reserved.',
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service',
      faq: 'FAQ',
      // Hotel specific translations
      hotelName: 'Hotel Name',
      rating: 'Rating',
      address: 'Address',
      website: 'Website',
      priceRange: 'Price Range',
      description: 'Description',
      amenities: 'Amenities',
      // Trip planning translations
      nextTrip: 'Next Trip Planning',
      destinations: 'Trip Destination',
      joinTrip: 'Join us on this trip',
      tripDetails: 'Trip Details',
      countdown: 'Trip Countdown',
      ournexttrip: 'Our Next Trip',
      experienceRussia: 'Experience the diverse beauty and rich culture of Russia',
      // Image management
      Image: 'Image',
      Imageuploaded: 'Image uploaded',
      UploadImage: 'Upload Image',
       discoverRussia: 'Discover Russia',
      experienceRussia: 'Experience Russia',
      exploreCulture: 'Explore the rich culture, breathtaking landscapes, and unique experiences that make Russia extraordinary',
      comingSoon: 'Coming Soon',
      curatingExperiences: 'We\'re curating the best {category} experiences for you.',
      primeLocation: 'Prime Location',
      explore: 'Explore',
      viewAll: 'View All',
      loadingExperiences: 'Loading experiences...',
      
      // Category page translations
      backToDiscover: 'Back to Discover',
      searchPlaceholder: 'Search {category}...',
      filters: 'Filters',
      filterAndSort: 'Filter & Sort',
      sortBy: 'Sort By',
      featured: 'Featured',
      rating: 'Rating',
      priceLowToHigh: 'Price: Low to High',
      priceHighToLow: 'Price: High to Low',
      priceRange: 'Price Range',
      allPrices: 'All Prices',
      budget: 'Budget',
      moderate: 'Moderate',
      expensive: 'Expensive',
      luxury: 'Luxury',
      minimumRating: 'Minimum Rating',
      allRatings: 'All Ratings',
      starsAndAbove: '{rating} ★ & above',
      clearAllFilters: 'Clear All Filters',
      results: '{count} {results}',
      result: 'Result',
      resultsPlural: 'Results',
      premiumExperiences: 'Premium experiences curated for you',
      noResultsFound: 'No Results Found',
      adjustFilters: 'Try adjusting your filters or search terms',
      clearSearch: 'Clear Search',
      multipleLocations: 'Multiple Locations',
      sortedBy: 'Sorted by {sort}',
      
      // Detail page translations
      aboutExperience: 'About This Experience',
      whatMakesSpecial: 'What Makes This Special',
      personalizedConcierge: 'Personalized concierge service available 24/7',
      exclusiveAccess: 'Exclusive access to local experiences and tours',
      flexibleBooking: 'Flexible booking and cancellation policy',
      amenitiesServices: 'Amenities & Services',
      allAmenities: 'All',
      essentialAmenities: 'Essential',
      luxuryAmenities: 'Luxury',
      contactInformation: 'Contact Information',
      phoneNumber: 'Phone',
      addressLocation: 'Address',
      website: 'Website',
      availability: 'Availability',
      checkRealTime: 'Check real-time availability',
      safetyGuidelines: 'Safety & Guidelines',
      covidSafety: 'COVID-19 safety measures in place',
      contactlessCheckin: 'Contactless check-in available',
      enhancedCleaning: 'Enhanced cleaning protocol',
      bookYourStay: 'Book Your Stay',
      checkIn: 'Check-in',
      checkOut: 'Check-out',
      guests: 'Guests',
      rooms: 'Rooms',
      totalPrice: 'Total Price',
      includesTaxes: 'for 5 nights • Includes taxes & fees',
      saveAmount: 'Save $499',
      cancel: 'Cancel',
      confirmBooking: 'Confirm Booking',
      experienceNotFound: 'Experience Not Found',
      notFoundMessage: 'The experience you\'re looking for doesn\'t exist or has been removed.',
      goBack: 'Go Back',
      loadingDetails: 'Loading experience details...',
      bookNow: 'Book Now',
      saveForLater: 'Save for Later',
      bookExperience: 'Book Experience',
      perNight: 'per night',
      excellentReviews: 'Excellent • 128 reviews',
      visitWebsite: 'Visit Website',
      
      // Hotel specific
      fromPrice: 'From $299',
      personalizedService: 'Personalized concierge service available 24/7',
      exclusiveTours: 'Exclusive access to local experiences and tours',
      flexibleCancellation: 'Flexible booking and cancellation policy',
      
      // Card actions
      share: 'Share',
      bookmark: 'Bookmark',
      favorite: 'Favorite',
      
      // Categories
      premiumRestaurants: 'Premium Restaurants',
      luxuryHotels: 'Luxury Hotels',
      culturalMuseums: 'Cultural Museums',
      discoverExperiences: 'Discover',
      explorePremium: 'Explore premium experiences',
      restaurantDescription: 'Discover exceptional dining experiences across Russia',
      hotelDescription: 'Experience world-class hospitality and accommodations',
      museumDescription: 'Explore Russia\'s rich history and artistic heritage',
      
      // Category types
      touristAttractions: 'Tourist Attractions',
      events: 'Events',
      shopping: 'Shopping',
      museums: 'Museums',
      naturalPlaces: 'Natural Places',
      
      // Booking modal
      guest: 'Guest',
      guestsPlural: 'Guests',
      room: 'Room',
      roomsPlural: 'Rooms',
      off: 'off',
      
      // Amenities
      freeWifi: 'Free WiFi',
      swimmingPool: 'Swimming Pool',
      spaWellness: 'Spa & Wellness',
      fitnessCenter: 'Fitness Center',
      restaurantAmenity: 'Restaurant',
      parkingAmenity: 'Parking',
      petFriendly: 'Pet Friendly',
      airConditioning: 'Air Conditioning',
      smartTV: 'Smart TV',
      breakfastIncluded: 'Breakfast Included',
      concierge24: '24/7 Concierge'
    },
    ar: {
      home: 'الرئيسية',
      services: 'الخدمات',
      plans: 'الخطط',
      transportation: 'النقل',
      hotels: 'الفنادق',
      residence: 'الإقامة',
      contact: 'اتصل بنا',
      getToKnowRussia: 'تعرف على روسيا',
      restaurants: 'المطاعم',
      touristAttractions: 'المعالم السياحية',
      events: 'الفعاليات',
      shopping: 'التسوق',
      museums: 'المتاحف',
      naturalPlaces: 'الأماكن الطبيعية',
      adminLogin: 'تسجيل الدخول كمسؤول',
      shareOnSocial: 'مشاركة على وسائل التواصل',
      companyLocation: 'موقع الشركة',
      viewOnMap: 'عرض على خرائط جوجل',
      // Hero section translations
      heroTitle: 'روينتو للسياحة',
      heroDescription: 'جرب روسيا كما لم يحدث من قبل مع خدماتنا السياحية المميزة. كأفضل مزود للخدمات السياحية المتخصصة في الوجهات الروسية، نقدم تجارب مصممة بدقة تمزج بين التراث الثقافي الغني، والمناظر الطبيعية الخلابة، والضيافة التي لا مثيل لها.',
      contactUs: 'اتصل بنا',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      signin: 'تسجيل الدخول',
      signingin: 'جاري تسجيل الدخول...',
      backtohome: '← العودة إلى الرئيسية',
      invalidCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
      loginSuccess: 'تم تسجيل الدخول بنجاح!',
      welcomeAdmin: 'مرحباً يا أدمن',
      dashboard: 'لوحة التحكم',
      logout: 'تسجيل الخروج',
      manageHeroVideo: 'إدارة الفيديو الرئيسي على الصفحة الرئيسية',
      updateTripInfo: 'تحديث معلومات تاريخ الرحلة القادمة',
      manageServices: 'إدارة بطاقات الخدمات (الخطط، النقل، إلخ)',
      manageRussiaCategories: 'إدارة فئات روسيا (المطاعم، المتاحف، إلخ)',
      manageBlogPosts: 'إنشاء وإدارة المقالات',
      manageTranslations: 'إدارة الترجمات والمحتوى اللغوي',
      manage: 'إدارة',
      recentActivity: 'النشاط الحديث',
      heroSection: 'القسم الرئيسي',
      russiaCategories: 'فئات روسيا',
      blogPosts: 'المقالات',
      languageContent: 'المحتوى اللغوي',
      ourServices: 'خدماتنا',
      servicesDescription: 'اكتشف خدمات السفر الشاملة المصممة لجعل مغامرتك الروسية لا تنسى',
      learnMore: 'اعرف المزيد',
      noServices: 'لا توجد خدمات متاحة في الوقت الحالي. يرجى التحقق مرة أخرى لاحقًا.',
      discoverRussia: 'اكتشف الجمال المتنوع والثقافة الغنية لروسيا من خلال معالمها العديدة',
      addItem: 'إضافة عنصر',
      noItems: 'لم تتم إضافة أي عناصر بعد. انقر فوق "إضافة عنصر" للبدء.',
      item: 'العنصر',
      images: 'الصور',
      uploadImage: 'تحميل الصورة',
      saving: 'جاري الحفظ...',
      save: 'حفظ التغييرات',
      noContent: 'لا يوجد محتوى متاح لهذه الفئة بعد.',
      manageBlog: 'إدارة المدونة',
      createBlog: 'إنشاء مقال جديد',
      editBlog: 'تعديل المقال',
      existingBlogs: 'المقالات الحالية',
      noBlogs: 'لا توجد مقالات بعد. أنشئ مقالك الأول!',
      by: 'بواسطة',
      title: 'العنوان',
      author: 'المؤلف',
      excerpt: 'ملخص',
      content: 'المحتوى',
      create: 'إنشاء',
      update: 'تحديث',
      cancel: 'إلغاء',
      blog: 'المدونة',
      blogDescription: 'اكتشف آخر الأخبار والنصائح والقصص حول السفر في روسيا',
      blogNotFound: 'المقال غير موجود',
      backToBlog: 'العودة إلى المدونة',
      readMore: 'اقرأ المزيد',
      latestFromBlog: 'الأحدث من مدونتنا',
      blogSectionDescription: 'اكتشف نصائح السفر، ورؤى ثقافية، ووجهات مثيرة في روسيا',
      viewAllBlogs: 'عرض جميع المقالات',
      contactDescription: 'تواصل معنا لأي أسئلة حول خدماتنا أو التخطيط لرحلتك القادمة إلى روسيا',
      getInTouch: 'ابق على تواصل',
      phone: 'الهاتف',
      address: 'العنوان',
      officeHours: 'ساعات العمل',
      hours: 'الإثنين - الجمعة: 9 صباحًا - 6 مساءً',
      visitUs: 'زورنا',
      mapPlaceholder: 'ستظهر هنا خريطة تفاعلية',
      sendMessage: 'أرسل لنا رسالة',
      yourName: 'اسمك',
      yourEmail: 'بريدك الإلكتروني',
      subject: 'الموضوع',
      message: 'الرسالة',
      sending: 'جاري الإرسال...',
      contactSuccess: 'شكرًا لك على رسالتك! سوف نعود إليك قريبًا.',
      footerDescription: 'جرب روسيا كما لم يحدث من قبل مع خدماتنا السياحية المميزة. اكتشف جمال وثقافة روسيا مع مرشدين خبراء.',
      quickLinks: 'روابط سريعة',
      discoverRussia: 'اكتشف روسيا',
      contactInfo: 'معلومات الاتصال',
      newsletter: 'اشترك في نشرتنا الإخبارية',
      newsletterDescription: 'احصل على آخر الأخبار والتحديثات حول خدماتنا وعروضنا.',
      subscribe: 'اشترك',
      allRightsReserved: 'جميع الحقوق محفوظة.',
      privacyPolicy: 'سياسة الخصوصية',
      termsOfService: 'شروط الخدمة',
      faq: 'الأسئلة الشائعة',
      // Hotel specific translations
      hotelName: 'اسم الفندق',
      rating: 'التقييم',
      address: 'العنوان',
      website: 'الموقع الإلكتروني',
      priceRange: 'نطاق السعر',
      description: 'الوصف',
      amenities: 'المرافق',
      // Trip planning translations
      nextTrip: 'تخطيط الرحلة القادمة',
      destinations: 'وجهة الرحلة',
      joinTrip: 'انضم إلينا في هذه الرحلة',
      tripDetails: 'تفاصيل الرحلة',
      countdown: 'العد التنازلي للرحلة',
      ournexttrip: 'رحلتنا القادمة',
      experienceRussia: 'استمتع بجمال المناظر الطبيعية المتنوعة والثقافة الغنية في روسيا',
      // Image management
      Image: 'الصور',
      Imageuploaded: 'تم تحميل الصورة',
      UploadImage: 'تحميل الصور',
       discoverRussia: 'اكتشف روسيا',
      experienceRussia: 'جرب روسيا',
      exploreCulture: 'استكشف الثقافة الغنية، والمناظر الطبيعية الخلابة، والتجارب الفريدة التي تجعل روسيا استثنائية',
      comingSoon: 'قريباً',
      curatingExperiences: 'نحن نعد أفضل تجارب {category} لك.',
      primeLocation: 'موقع ممتاز',
      explore: 'استكشف',
      viewAll: 'عرض الكل',
      loadingExperiences: 'جاري تحميل التجارب...',
      
      // Category page translations
      backToDiscover: 'العودة إلى الاكتشاف',
      searchPlaceholder: 'ابحث في {category}...',
      filters: 'الفلترة',
      filterAndSort: 'فلترة وترتيب',
      sortBy: 'ترتيب حسب',
      featured: 'مميز',
      rating: 'التقييم',
      priceLowToHigh: 'السعر: من الأقل للأعلى',
      priceHighToLow: 'السعر: من الأعلى للأقل',
      priceRange: 'نطاق السعر',
      allPrices: 'جميع الأسعار',
      budget: 'اقتصادي',
      moderate: 'متوسط',
      expensive: 'مكلف',
      luxury: 'فاخر',
      minimumRating: 'أقل تقييم',
      allRatings: 'جميع التقييمات',
      starsAndAbove: '{rating} ★ فما فوق',
      clearAllFilters: 'مسح جميع الفلاتر',
      results: '{count} {results}',
      result: 'نتيجة',
      resultsPlural: 'نتائج',
      premiumExperiences: 'تجارب مميزة مختارة لك',
      noResultsFound: 'لم يتم العثور على نتائج',
      adjustFilters: 'حاول تعديل الفلاتر أو مصطلحات البحث',
      clearSearch: 'مسح البحث',
      multipleLocations: 'مواقع متعددة',
      sortedBy: 'مرتب حسب {sort}',
      
      // Detail page translations
      aboutExperience: 'حول هذه التجربة',
      whatMakesSpecial: 'ما الذي يجعلها مميزة',
      personalizedConcierge: 'خدمة الكونسيرج الشخصية متاحة 24/7',
      exclusiveAccess: 'وصول حصري للتجارب المحلية والجولات',
      flexibleBooking: 'سياسة حجز وإلغاء مرنة',
      amenitiesServices: 'المرافق والخدمات',
      allAmenities: 'الكل',
      essentialAmenities: 'أساسي',
      luxuryAmenities: 'فاخر',
      contactInformation: 'معلومات الاتصال',
      phoneNumber: 'الهاتف',
      addressLocation: 'العنوان',
      website: 'الموقع الإلكتروني',
      availability: 'التوافر',
      checkRealTime: 'تحقق من التوافر في الوقت الفعلي',
      safetyGuidelines: 'إرشادات السلامة',
      covidSafety: 'إجراءات السلامة من كوفيد-19 مطبقة',
      contactlessCheckin: 'تسجيل الوصول بدون تلامس متاح',
      enhancedCleaning: 'بروتوكول تنظيف معزز',
      bookYourStay: 'احجز إقامتك',
      checkIn: 'تاريخ الوصول',
      checkOut: 'تاريخ المغادرة',
      guests: 'الضيوف',
      rooms: 'الغرف',
      totalPrice: 'السعر الإجمالي',
      includesTaxes: 'لمدة 5 ليالي • يشمل الضرائب والرسوم',
      saveAmount: 'وفر $499',
      cancel: 'إلغاء',
      confirmBooking: 'تأكيد الحجز',
      experienceNotFound: 'التجربة غير موجودة',
      notFoundMessage: 'التجربة التي تبحث عنها غير موجودة أو تمت إزالتها.',
      goBack: 'العودة',
      loadingDetails: 'جاري تحميل تفاصيل التجربة...',
      bookNow: 'احجز الآن',
      saveForLater: 'حفظ لوقت لاحق',
      bookExperience: 'احجز التجربة',
      perNight: 'لليلة الواحدة',
      excellentReviews: 'ممتاز • 128 تقييم',
      visitWebsite: 'زيارة الموقع',
      
      // Hotel specific
      fromPrice: 'بداية من $299',
      personalizedService: 'خدمة الكونسيرج الشخصية متاحة 24/7',
      exclusiveTours: 'وصول حصري للتجارب المحلية والجولات',
      flexibleCancellation: 'سياسة حجز وإلغاء مرنة',
      
      // Card actions
      share: 'مشاركة',
      bookmark: 'حفظ',
      favorite: 'مفضلة',
      
      // Categories
      premiumRestaurants: 'مطاعم مميزة',
      luxuryHotels: 'فنادق فاخرة',
      culturalMuseums: 'متاحف ثقافية',
      discoverExperiences: 'اكتشف',
      explorePremium: 'استكشف تجارب مميزة',
      restaurantDescription: 'اكتشف تجارب تناول الطعام الاستثنائية في جميع أنحاء روسيا',
      hotelDescription: 'جرب الضيافة والإقامة على مستوى عالمي',
      museumDescription: 'استكشف التاريخ الغني والتراث الفني لروسيا',
      
      // Category types
      events: 'الفعاليات',
      shopping: 'التسوق',
      museums: 'المتاحف',
      naturalPlaces: 'الأماكن الطبيعية',
      readMore: 'اقرأ المزيد',
readLess: 'اقرأ أقل',
loadingServices: 'جاري تحميل الخدمات المميزة...',
premiumService: 'خدمة مميزة',
serviceDescriptionDefault: 'جرب خدمة عالمية المستوى مع عروضنا المميزة، المصممة لأكثر العملاء تميزاً.',
premiumFeatures: 'الميزات المميزة',
personalizedConcierge: 'خدمة كونسيرج شخصية متاحة 24/7',
VIPSecurity: 'أمن خاص',
concierge24: 'كونسيرج 24/7',
DedicatedSupport: 'دعم مخصص',
from: 'بداية من',
customPricing: 'أسعار مخصصة متاحة',
enquireNow: 'استفسر الآن',
scrollToExplore: 'قم بالتمرير لاستكشاف جميع الخدمات ←',
      // Booking modal
      guest: 'ضيف',
      guestsPlural: 'ضيوف',
      room: 'غرفة',
      roomsPlural: 'غرف',
      off: 'خصم',

      // Amenities
      freeWifi: 'واي فاي مجاني',
      swimmingPool: 'حمام سباحة',
      spaWellness: 'سبا وعناية بالصحة',
      fitnessCenter: 'مركز لياقة بدنية',
      restaurantAmenity: 'مطعم',
      parkingAmenity: 'موقف سيارات',
      petFriendly: 'مسموح بالحيوانات الأليفة',
      airConditioning: 'تكييف هواء',
      smartTV: 'تلفزيون ذكي',
      breakfastIncluded: 'الإفطار مشمول',
      concierge24: 'كونسيرج 24/7',
      hotelAmenities: 'مرافق الفندق',
addCustomAmenity: 'إضافة مرفق مخصص',
selectedAmenities: 'المرافق المختارة',
uploadImageSuccess: 'تم تحميل الصورة بنجاح!',
uploadImageError: 'خطأ في تحميل الصورة',
categoryUpdated: 'تم تحديث {category} بنجاح!',
categoryUpdateError: 'خطأ في تحديث {category}',
backToServices: 'العودة إلى الخدمات',
quickFacts: 'حقائق سريعة',
duration: 'المدة',
groupSize: 'حجم المجموعة',
availability: 'التوفر',
locations: 'المواقع',
overview: 'نظرة عامة',
whatsIncluded: 'ما المضمن',
startingFrom: 'بداية من',
customPackagesAvailable: 'باقات مخصصة متاحة',
bookNow: 'احجز الآن',
requestQuote: 'اطلب عرض سعر',
detailedItinerary: 'برنامج الرحلة التفصيلي',
needHelp: 'تحتاج مساعدة؟',
callUs: 'اتصل بنا',
emailUs: 'راسلنا',
liveChat: 'دردشة مباشرة',
whyChooseThisService: 'لماذا تختار هذه الخدمة؟',
bestPriceGuarantee: 'ضمان أفضل سعر',
flexibleCancellation: 'إلغاء مرن',
localExpertGuides: 'مرشدين محليين خبراء',
sustainableTourism: 'سياحة مستدامة',
expertLocalGuides: 'مرشدين محليين خبراء',
comfortableAccommodations: 'إقامة مريحة',
allTransportationIncluded: 'جميع وسائل النقل مشمولة',
entryFeesToAttractions: 'رسوم دخول المعالم السياحية',
traditionalMeals: 'وجبات تقليدية',
support24_7: 'دعم على مدار الساعة',
available24_7: 'متاح 24/7',
day1: 'اليوم الأول',
day2: 'اليوم الثاني',
day3: 'اليوم الثالث',
day4: 'اليوم الرابع',
day5: 'اليوم الخامس',
arrivalWelcome: 'الوصول والترحيب',
cityExploration: 'استكشاف المدينة',
culturalImmersion: 'الانغماس الثقافي',
naturalWonders: 'عجائب الطبيعة',
departure: 'المغادرة',
arrivalWelcomeDesc: 'استقبال من المطار وعشاء ترحيبي تقليدي',
cityExplorationDesc: 'جولة إرشادية في المواقع التاريخية والأسواق المحلية',
culturalImmersionDesc: 'ورش عمل تقليدية وعروض ثقافية',
naturalWondersDesc: 'رحلة يومية إلى المناظر الطبيعية الخلابة والمحميات الطبيعية',
departureDesc: 'الإفطار النهائي ونقل إلى المطار',
book: 'احجز',
fillDetails: 'املأ تفاصيلك وسنتواصل معك قريبًا',
fullName: 'الاسم الكامل',
emailAddress: 'البريد الإلكتروني',
phoneNumber: 'رقم الهاتف',
startDate: 'تاريخ البدء',
travelers: 'المسافرين',
specialRequests: 'طلبات خاصة',
submitBooking: 'إرسال الحجز',
perPerson: 'للشخص',
durationDefault: '3-7 أيام',
groupSizeDefault: '2-12 شخص',
availabilityDefault: 'على مدار العام',
locationsDefault: 'متعدد',
serviceTitle: 'عنوان الخدمة',
serviceDescriptionDefault: 'سيظهر وصف الخدمة هنا.',
premiumServices: 'خدمات مميزة',
    
    }
  };

  const toggleLanguage = () => {
    setCurrentLanguage(prevLang => prevLang === 'en' ? 'ar' : 'en');
  };

  const value = {
    currentLanguage,
    toggleLanguage,
    translations: translations[currentLanguage]
  };

  return (
    <LanguageContext.Provider value={value}>
      <div dir={currentLanguage === 'ar' ? 'rtl' : 'ltr'} className={currentLanguage === 'ar' ? 'font-arabic' : 'font-sans'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export { LanguageContext };